name: Daily FMKorea Scraper

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Chrome + Chromedriver
        run: |
          sudo apt update
          sudo apt install -y wget unzip xvfb default-jdk libxi6
      
          # ✅ Chrome 설치
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb || true
      
          # ✅ chromedriver 설치
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
          echo "🔧 Chrome version: $CHROME_VERSION"
          wget -q https://chromedriver.storage.googleapis.com/$CHROME_VERSION/chromedriver_linux64.zip || true
          unzip -o chromedriver_linux64.zip || true
          sudo mv chromedriver /usr/local/bin/ || true
          sudo chmod +x /usr/local/bin/chromedriver || true
      
          pip install -r requirements.txt



      - name: Run scraper
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          echo "✅ MONGO_URI from env: $MONGO_URI"
          python scrape_fmkorea.py

